/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    especialistas: Especialista;
    servicios: Servicio;
    testimonios: Testimonio;
    faqs: Faq;
    colegios: Colegio;
    promociones: Promocione;
    referidos: Referido;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    especialistas: EspecialistasSelect<false> | EspecialistasSelect<true>;
    servicios: ServiciosSelect<false> | ServiciosSelect<true>;
    testimonios: TestimoniosSelect<false> | TestimoniosSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    colegios: ColegiosSelect<false> | ColegiosSelect<true>;
    promociones: PromocionesSelect<false> | PromocionesSelect<true>;
    referidos: ReferidosSelect<false> | ReferidosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    configuracion: Configuracion;
    home: Home;
  };
  globalsSelect: {
    configuracion: ConfiguracionSelect<false> | ConfiguracionSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "especialistas".
 */
export interface Especialista {
  id: number;
  nombre: string;
  slug: string;
  profesion: string;
  colegiatura?: string | null;
  foto: number | Media;
  frase?: string | null;
  bio?: string | null;
  especialidades?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  anos_experiencia?: number | null;
  servicios?: (number | Servicio)[] | null;
  whatsapp?: string | null;
  correo?: string | null;
  instagram?: string | null;
  atiende_online?: boolean | null;
  nfc_id?: string | null;
  orden?: number | null;
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicios".
 */
export interface Servicio {
  id: number;
  nombre: string;
  slug: string;
  descripcion_corta: string;
  descripcion_larga?: string | null;
  imagen?: (number | null) | Media;
  icono?: (number | null) | Media;
  edades?: string | null;
  motivos_consulta?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  duracion_sesion?: string | null;
  frecuencia?: string | null;
  anos_experiencia?: string | null;
  especialistas?: (number | Especialista)[] | null;
  mostrar_precio?: boolean | null;
  precio?: string | null;
  orden?: number | null;
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonios".
 */
export interface Testimonio {
  id: number;
  nombre: string;
  texto: string;
  calificacion?: number | null;
  especialista?: (number | null) | Especialista;
  servicio?: (number | null) | Servicio;
  fecha?: string | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  pregunta: string;
  respuesta: string;
  categoria: 'general' | 'servicios' | 'pagos' | 'promociones';
  servicio?: (number | null) | Servicio;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colegios".
 */
export interface Colegio {
  id: number;
  nombre: string;
  contacto?: string | null;
  telefono?: string | null;
  correo?: string | null;
  direccion?: string | null;
  codigo_referido: string;
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promociones".
 */
export interface Promocione {
  id: number;
  titulo: string;
  slug: string;
  descripcion: string;
  imagen?: (number | null) | Media;
  fecha_inicio: string;
  fecha_fin: string;
  descuento?: string | null;
  codigo?: string | null;
  colegio?: (number | null) | Colegio;
  reglas?: string | null;
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referidos".
 */
export interface Referido {
  id: number;
  paciente_nombre: string;
  paciente_contacto: string;
  codigo: string;
  colegio?: (number | null) | Colegio;
  especialista?: (number | null) | Especialista;
  servicio?: (number | null) | Servicio;
  fecha: string;
  estado: 'pendiente' | 'aplicado' | 'vencido';
  notas?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'especialistas';
        value: number | Especialista;
      } | null)
    | ({
        relationTo: 'servicios';
        value: number | Servicio;
      } | null)
    | ({
        relationTo: 'testimonios';
        value: number | Testimonio;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'colegios';
        value: number | Colegio;
      } | null)
    | ({
        relationTo: 'promociones';
        value: number | Promocione;
      } | null)
    | ({
        relationTo: 'referidos';
        value: number | Referido;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "especialistas_select".
 */
export interface EspecialistasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  profesion?: T;
  colegiatura?: T;
  foto?: T;
  frase?: T;
  bio?: T;
  especialidades?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  anos_experiencia?: T;
  servicios?: T;
  whatsapp?: T;
  correo?: T;
  instagram?: T;
  atiende_online?: T;
  nfc_id?: T;
  orden?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicios_select".
 */
export interface ServiciosSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion_corta?: T;
  descripcion_larga?: T;
  imagen?: T;
  icono?: T;
  edades?: T;
  motivos_consulta?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  duracion_sesion?: T;
  frecuencia?: T;
  anos_experiencia?: T;
  especialistas?: T;
  mostrar_precio?: T;
  precio?: T;
  orden?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonios_select".
 */
export interface TestimoniosSelect<T extends boolean = true> {
  nombre?: T;
  texto?: T;
  calificacion?: T;
  especialista?: T;
  servicio?: T;
  fecha?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  pregunta?: T;
  respuesta?: T;
  categoria?: T;
  servicio?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colegios_select".
 */
export interface ColegiosSelect<T extends boolean = true> {
  nombre?: T;
  contacto?: T;
  telefono?: T;
  correo?: T;
  direccion?: T;
  codigo_referido?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promociones_select".
 */
export interface PromocionesSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  descripcion?: T;
  imagen?: T;
  fecha_inicio?: T;
  fecha_fin?: T;
  descuento?: T;
  codigo?: T;
  colegio?: T;
  reglas?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referidos_select".
 */
export interface ReferidosSelect<T extends boolean = true> {
  paciente_nombre?: T;
  paciente_contacto?: T;
  codigo?: T;
  colegio?: T;
  especialista?: T;
  servicio?: T;
  fecha?: T;
  estado?: T;
  notas?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion".
 */
export interface Configuracion {
  id: number;
  nombre_consultorio?: string | null;
  eslogan?: string | null;
  logo?: (number | null) | Media;
  historia?: string | null;
  mision?: string | null;
  vision?: string | null;
  direccion?: string | null;
  punto_referencia?: string | null;
  telefono?: string | null;
  whatsapp?: string | null;
  correo?: string | null;
  instagram?: string | null;
  horarios?: string | null;
  google_maps_embed?: string | null;
  google_maps_url?: string | null;
  google_review_url?: string | null;
  seo_titulo?: string | null;
  seo_descripcion?: string | null;
  seo_imagen?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero_titulo?: string | null;
  hero_subtitulo?: string | null;
  hero_imagen?: (number | null) | Media;
  hero_cta_texto?: string | null;
  hero_cta_url?: string | null;
  anos_experiencia?: string | null;
  familias_atendidas?: string | null;
  calificacion_promedio?: string | null;
  mostrar_bloque_colegios?: boolean | null;
  colegios_titulo?: string | null;
  colegios_texto?: string | null;
  colegios_imagen?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion_select".
 */
export interface ConfiguracionSelect<T extends boolean = true> {
  nombre_consultorio?: T;
  eslogan?: T;
  logo?: T;
  historia?: T;
  mision?: T;
  vision?: T;
  direccion?: T;
  punto_referencia?: T;
  telefono?: T;
  whatsapp?: T;
  correo?: T;
  instagram?: T;
  horarios?: T;
  google_maps_embed?: T;
  google_maps_url?: T;
  google_review_url?: T;
  seo_titulo?: T;
  seo_descripcion?: T;
  seo_imagen?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero_titulo?: T;
  hero_subtitulo?: T;
  hero_imagen?: T;
  hero_cta_texto?: T;
  hero_cta_url?: T;
  anos_experiencia?: T;
  familias_atendidas?: T;
  calificacion_promedio?: T;
  mostrar_bloque_colegios?: T;
  colegios_titulo?: T;
  colegios_texto?: T;
  colegios_imagen?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}